import "./globals.css";
export const metadata = {
  icons: {
    icon: "/favicon/favico.ico",
  },
  title: "Hirsad",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head> */}
      <body>{children}</body>
    </html>
  );
}
